jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '1.8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: scp
        uses: garygrossgarten/github-action-scp@release
        env:
          SSH_PRIVATE_KEY: ${{ secrets.TIANYI_SERVER_ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "public"
          REMOTE_HOST: 218.78.55.64
          REMOTE_USER: "root"
          TARGET: "/usr/opt"