name: Java Deploy with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        # 这里使用java11的环境, 其他项目在github action中找到对应的语言环境就行
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        # 这里maven的打包命令, 其他项目修改为对应的打包命令
        run: |
          mvn package
      - name: Deploy to tianyi cloud server
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{secrets.TIANYI_SERVER_IP}}
          port: 22
          username: root
          password: ${{ secrets.TIANYI_SERVER_PWD }}
          scp_source: ./public/
          scp_target: "/usr/opt"
