name: Java Deploy with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        # 这里使用java11的环境, 其他项目在github action中找到对应的语言环境就行
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build with Maven
        # 这里maven的打包命令, 其他项目修改为对应的打包命令
        run: |
          mvn package
      - name: Deploy to tianyi cloud server
        uses: easingthemes/ssh-deploy@v2.0.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.TIANYI_SERVER_ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "public"
          REMOTE_HOST: "218.78.55.64"
          REMOTE_USER: "root"
          TARGET: "/usr/opt"